# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton
import configparser
import time
import cv2
import numpy
import os

ilist = ['image/1.png', 'image/2.png', 'image/3.png', 'image/4.png', 'image/5.png', 'image/6.png', 'image/7.png', 'image/8.png', 'image/9.png', 'image/0.png']
count = 0

class secondwindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(414, 730)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(55, 600, 200, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(55, 640, 200, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 389, 512))
        self.label_3.setObjectName("label_3")
        self.btn = QPushButton(self.centralwidget)
        self.btn.setGeometry(275, 600, 75, 61)
        self.btn.setObjectName("pushButton")
        self.btn.clicked.connect(self.ishow)

    # def ishow(self):
    #     global ilist, count
    #     self.label_3.setPixmap(QtGui.QPixmap(ilist[count]))
    #     print(count)
    #     count += 1
    #     if count == 10:
    #         cqount = 0
        
    # def ishow(self):
    #     iilist = 'image/Untitled.png'
    #     image = cv2.imread(iilist)
    #     print(type(image))
    #     cv2.imshow('AI', image)        
    #     #cv2.waitKey(1000)
    


    def ishow(self):
        filelist = os.listdir('C:\\study\\20240130')        
        print(filelist)
        while True:
            for i in filelist:            
                if i.endswith(".png"):
                    image = cv2.imread(i)
                    cv2.imshow('AI', image)  
                    cv2.waitKey(1000)
                    print(i)
            if cv2.waitKey(1000) & 0xFF == ord('q'):
                print("wait진입")
                break
        

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(414, 730)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

         
        self.label_1.setPixmap(QtGui.QPixmap("image/Untitled.png"))

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(104, 50, 209, 200))
        self.label_4.setObjectName("label_4")
        # self.label_4.setPixmap(QtGui.QPixmap("test.png"))

        # self.label = QtWidgets.QLabel(self.centralwidget)
        # self.label.setGeometry(QtCore.QRect(78, 540, 31, 31))
        # self.label.setObjectName("label")

        # self.label_2 = QtWidgets.QLabel(self.centralwidget)
        # self.label_2.setGeometry(QtCore.QRect(78, 580, 31, 31))
        # self.label_2.setObjectName("label_2")

        self.btn = QPushButton(self.centralwidget)
        self.btn.setGeometry(260, 550, 80, 21)
        self.btn.setObjectName("PushButton")
        self.btn.clicked.connect(self.open)

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(95, 550, 131, 21))
        self.label_3.setObjectName("label_3")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(175, 452, 173, 21))
        self.lineEdit.setObjectName("lineEdit")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(175, 504, 173, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.returnPressed.connect(self.open2)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def open(self):
        config = configparser.ConfigParser()
        config.read("test.ini")
        pid = config['user']['id']
        # print("pid값은 뭐니?", pid)
        ppw = config["user"]['pw']
        # print("ppw값은 뭐니?", ppw)
        text = self.lineEdit.text()
        text2 = self.lineEdit_2.text()

        if pid == text and ppw == text2:
            self.label_3.setText("open")
            self.label_4.setHidden(False)
            self.label_4.setPixmap(QtGui.QPixmap("image/test.png"))

            self.window = QtWidgets.QWidget()
            self.ui = secondwindow()
            self.ui.setupUi(self.window)
            self.window.show()


        else :
            self.label_3.setText("Close")
            self.label_4.setHidden(True)

    def open2(self):
        config = configparser.ConfigParser()
        config.read("test.ini")
        pid = config['user']['id']
        ppw = config["user"]['pw']
        text = self.lineEdit.text()
        text2 = self.lineEdit_2.text()

        if pid == text and ppw == text2:
            self.label_3.setText("open")
            self.label_4.setHidden(False)
            self.label_4.setPixmap(QtGui.QPixmap("image/test.png"))

            self.window = QtWidgets.QWidget()
            self.ui = secondwindow()
            self.ui.setupUi(self.window)
            self.window.show()
            MainWindow.hide()

        else :
            self.label_3.setText("Close")
            self.label_4.setHidden(True)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.label.setText(_translate("MainWindow", "ID"))
        # self.label_2.setText(_translate("MainWindow", "PW"))
        self.label_3.setText(_translate("MainWindow", "result"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
