# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThread, pyqtSignal, Qt
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QPushButton, QListWidget
from openpyxl import load_workbook
from datetime import datetime
from glob import glob
import os
import time
import subprocess
import threading
import sys
import socket
import time
import psutil
import ctypes
import glob
import shutil

class App(QtWidgets.QWidget):
    """메인 윈도우"""
    qss = """
        QWidget {
            color: #000000;
            background: #111;
        }
        QWidget#windowTitle {
            color: #FFFFFF;
            background: #333;
        }
        QWidget#windowTitle QLabel {
            color: #FFFFFF;
            background: #333;
        }
    """
    def __init__(self):
        super().__init__()
        #self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.setStyleSheet(self.qss)
        self.title = 'Wiirow_Retry_Program'
        self.left = 0
        self.top = 0
        self.width = 1920
        self.height = 1080
        self.initUI()

    def initUI(self):
        while True:
            for q in psutil.process_iter():
                try:
                    if q.name() == 'notepad.exe':
                        if len(q.cmdline()) > 1 and 'notepad.exe' in q.cmdline()[1]:
                            print("존재")
                    else :
                        print("존재하지 않음")
                        os.system("notepad.exe")

                except psutil.AccessDenied:
                    continue
            time.sleep(5)

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    ex = App()
    ex.show()
    sys.exit(app.exec_())