# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from sqlite3 import Error
import cv2


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(350, 380, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        
        
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(375,500,50,30)
        self.btn.setObjectName("PushButton")
        self.btn.clicked.connect(self.stop1)
        self.btn.setText('stop')

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.stop = 0
        self.lineEdit.returnPressed.connect(self.open)

    def open(self):
        text = self.lineEdit.text()
        conn = sqlite3.connect('friend.db')
        cur = conn.cursor()
        cur.execute("SELECT * FROM CCND")
        rows = cur.fetchall()
        for row in rows:
            if row[0] == text:
                path = row[5]
                cap = cv2.VideoCapture(path)
                if cap.isOpened():
                    while True:
                        ret, img = cap.read()
                        if ret:
                            cv2.imshow(path, img)
                            cv2.waitKey(33)
                        if self.stop ==1 or cv2.getWindowProperty(path, cv2.WND_PROP_VISIBLE ) <1:
                            self.stop=0
                            break
                else:
                    print('can not')
                    
                cap.release()
                cv2.destroyAllWindows()
    def stop1(self):
        self.stop = 1             
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
